name: tirnav
version: 1.0.0+1
description: TIRNAV - TIR ve ağır vasıta sürücüleri için navigasyon.
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.2
  latlong2: ^0.9.1
  geolocator: ^14.0.3
  http: ^1.6.0

flutter:
  uses-material-design: true

